package sk.uniba.fmph.dcs.stone_age;

public enum ImmediateEffect {
    THROW_WOOD, THROW_CLAY, THROW_STONE, THROW_GOLD, POINT, WOOD, CLAY, STONE, GOLD, CARD, ARBITRARY_RESOURCE, FOOD,
    ALL_PLAYERS_TAKE_REWARD, TOOL, ONE_TIME_TOOL2, ONE_TIME_TOOL3, ONE_TIME_TOOL4, FIELD,

}
